########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }


  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
 #   - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.png"
# meta data
author: "ivan-gentile"
description: "Ivan Gentile's personal blog, sharing insights on technology, science and AI. Dive in to explore my latest projects and thoughts."
# google analitycs ID
google_analitycs_id: "G-LD09G9SLPW" # your id
# contact form action
contact_form_action: "https://formspree.io/f/xbjvozjn" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2023 Designed and Developed by Ivan Gentile"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:

  - name: "twitter"
    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link: "https://twitter.com/gptheoryy"

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/ivan-gentile"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "https://www.linkedin.com/in/ivan-gentile/"

  - name: "youtube"
    icon: "ti-youtube" # themify icon pack https://themify.me/themify-icons
    link: "https://www.youtube.com/@gptheory"